In [9]:
# straight calculation
import numpy as np
import pandas as pd

data = pd.read_csv("gravitational_force_data.csv")
data = np.array(data)
m,n  = data.shape

np.random.shuffle(data)


data_dev = data[0:1000].T
y_dev = data_dev[3]
x_dev = data_dev[0:n-1]

data_train = data[1000:m].T
y_train = data_train[3]
x_train = data_train[0:n-1]


In [10]:
# necessary Functions

# Activation Functions
def relu(z):
    return np.maximum(z,0)

# Mean Square error
def calculate_mse(y,a2):
    # Ensure that y and are numpy arrays
    y = np.array(y)
    a2 = np.array(a2)
    mse = np.mean((y-a2)**2)
    return mse

# Activation Divergence function
def relu_div(z):
    return z>0




# Parameter Initialization
def init_params():
    w1 = np.random.rand(9,3) * np.sqrt(2./3)
    w2 = np.random.rand(9,9) * np.sqrt(2./6)
    w3 = np.random.rand(1,9) * np.sqrt(2./6)
    b1 = np.random.rand(9,1)
    b2 = np.random.rand(9,1)
    b3 = np.random.rand(1,1)
    return w1,w2,w3,b1,b2,b3

# Forward Propagation
def forward_prop(w1,w2,w3,b1,b2,b3,x):
    z1 = w1.dot(x) + b1
    a1 = relu(z1)
    z2 = w2.dot(z1)+ b2
    a2 = relu(z2)
    z3 = w3.dot(z2)+ b3
    return z1,z2,z3,a1,a2


# Error calculation
def calculate_mse(y_train, z3):
    # Ensure that y_train and a2 are numpy arrays
    y_train = np.array(y_train)
    z3 = np.array(z3)
    
    # Calculate the Mean Squared Error (MSE)
    mse = np.mean((y_train - z3) ** 2)
    
    return mse



# Backward Propagation
def back_prop(z1,z2,z3,a1,a2,w1,w2,w3,x,y):
    m,n = x_train.shape
    m,n = x_train.shape
    dz3 = y_train-z3
    dw3 = (1/m)*dz3.dot(a2.T)
    db3 = (1/m)*np.sum(dz3)
    dz2 = w3.T.dot(dz3) * relu_div(z2)
    dw2 = (1/m)*dz2.dot(a1.T)
    db2 = (1/m)*np.sum(dz2)
    dz1 = w2.T.dot(dz2) * relu_div(z1)
    dw1 = (1/m)*dz1.dot(x_train.T)
    db1 = (1/m)*np.sum(dz1)
    return dz3,dz2,dz1,dw3,dw2,dw1,db3,db2,db1


def update_params(w1,w2,w3,b1,b2,b3,dw1,dw2,dw3,db1,db2,db3,alpha):
    w1 = w1 - alpha*dw1
    b1 = b1 - alpha*db1
    w2 = w2 - alpha*dw2
    b2 = b2 - alpha*db2
    w3 = w3 - alpha*dw3
    b3 = b3 - alpha*db3
    return w1,w2,w3,b1,b2,b3


# Gradient descent
def grad_descent(x,y,iterations,alpha):
    w1,w2,w3,b1,b2,b3 = init_params()
    for i in range(iterations):
        z1,z2,z3,a1,a2 = forward_prop(w1,w2,w3,b1,b2,b3,x)
        dz3,dz2,dz1,dw3,dw2,dw1,db3,db2,db1 = back_prop(z1,z2,z3,a1,a2,w1,w2,w3,x,y)
        w1,w2,w3,b1,b2,b3 = update_params(w1,w2,w3,b1,b2,b3,dw1,dw2,dw3,db1,db2,db3,alpha)
        if(i%2 == 0):
            print("Iteration: ",i)
            predictions = z3
            print("Error: ", calculate_mse(y_train,z3))
    return w1,w2,w3,b1,b2,b3



[[ 8. 74. 58. ... 61. 86. 20.]
 [ 5. 15. 68. ... 38. 30. 70.]
 [ 8.  2. 27. ... 88. 32. 26.]]


In [11]:
w1,w2,w3,b1,b2,b3 = grad_descent(x_train,y_train,100,-0.00000000001)

Iteration:  0
Error:  264070.72064844833
Iteration:  2
Error:  830.4286828116236
Iteration:  4
Error:  108.50102371311843
Iteration:  6
Error:  15.070287478746792
Iteration:  8
Error:  2.804819185516094
Iteration:  10
Error:  1.19055763327749
Iteration:  12
Error:  0.9771446868160567
Iteration:  14
Error:  0.9480363367039938
Iteration:  16
Error:  0.9431793931718834
Iteration:  18
Error:  0.941515039774536
Iteration:  20
Error:  0.9402724159623562
Iteration:  22
Error:  0.9390869315978332
Iteration:  24
Error:  0.9379106104682501
Iteration:  26
Error:  0.9367371365516792
Iteration:  28
Error:  0.9355656755866755
Iteration:  30
Error:  0.9343961146431635
Iteration:  32
Error:  0.9332284357214314
Iteration:  34
Error:  0.9320626333232567
Iteration:  36
Error:  0.930898703603735
Iteration:  38
Error:  0.9297366429431572
Iteration:  40
Error:  0.9285764477588169
Iteration:  42
Error:  0.9274181144801584
Iteration:  44
Error:  0.9262616395454405
Iteration:  46
Error:  0.9251070194012745
Ite

In [14]:
print(x_train)
x = np.array([[2],[2],[2]])
z1,z2,z3,a1,a2 = forward_prop(w1,w2,w3,b1,b2,b3,x)
print(z3)

[[ 8. 74. 58. ... 61. 86. 20.]
 [ 5. 15. 68. ... 38. 30. 70.]
 [ 8.  2. 27. ... 88. 32. 26.]]
[[0.95935795]]
